### ISSUE TITLE
Update to latest Umami version

### ISSUE THREAD

**Issue by afonsosantos** [tschannik/caprover-umami#13]
Hi!
Can we update to the lastest version of Umami?

![image](https://user-images.githubusercontent.com/46262740/174438299-3a22ef9a-2855-4839-bdc9-66e02d6e6b6b.png)

Thanks!

**Comment by heyeddi** [comment]
use tag `postgres-latest` that will get the latest.

btw @tschannik, the instructions [here](https://umami.is/docs/running-on-caprover) tell us to check the tag on this repo to choose the umami verison, however the tag in this repo does not match the rag on dockerhub.

Tag here is `postgresql-latest` tag on docker hub is `postgres-latest`, which took me a while to figure out.
I created a PR to update the documentation https://github.com/umami-software/website/pull/55

Hope this helps!

**Comment by tschannik** [comment]
@Bass-03 thanks for updating the wiki!

I just went through the new [release of umami](https://github.com/mikecao/umami/releases/tag/v1.33).
There is a new script which automatically updates the database. Before this was a manual step and thats why i had to create this repository in the first place. 

I'm currently ooo because of educational reasons but afterwards i'll update the one-click-app for caprover with a different and more streamlined approach. 

I'll archive this repository soon afterwards.

**Comment by tschannik** [comment]
@afonsosantos Thanks for opening this issue. Please have a look at my previous comment. 
I'll add an update guide to the caprover section on the umami wiki when i have completed the change. This will also be valid for your setup. 

I'll update the issue as soon as possible

**Comment by heyeddi** [comment]
@tschannik thanks for that! I noticed `postgres-latest` is version 1.30, I only needed version 1.22 for the rename script feature, but would gladle take the latest.

**Comment by tschannik** [comment]
I just noticed that someone beat me to it. There are new one click apps on caprover for umami. Easiest way to use the new config is to replace your current instance and migrating the database manually if you still want the data. 

The other option is to keep the current setup and deploy the new version in the deployment tab with the docker image method. Use 
`ghcr.io/umami-software/umami:mysql-v1.36.1`
for mysql or 
`ghcr.io/umami-software/umami:postgres-v1.36.1`
for postgres. 

As far as i know the env variables should stay the same but i was not able to test it because i already replaced my installation without thinking about migrating. 

I will archive this repository now because it's already obsolete.
